name: Deploy Application
 
on:
  push:
    branches:
      - deployment
 
jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Build Docker images
        run: docker compose build
 
      - name: Start application
        run: docker compose up -d
 
      - name: Check containers
        run: docker compose ps
